apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: echo-ingress
    namespace: default
    annotations:
        # haproorwarded-for: 'true'
        # haproxy.org/loadxy.org/check: 'true'
        # haproxy.org/f-balance: leastconn
        # ingress.class: haproxy
        haproxy.org/path-rewrite: "/"
        # kubernetes.io/ingress.class: haproxy
spec:
    rules:
    - http:
        paths:
        - path: /echo
          pathType: Prefix
          backend:
            service:
              name: echo-service
              port:
                number: 8080
